### ISSUE TITLE
Не использовать исключения для управления потоком исполнения

### ISSUE THREAD

**Issue by AlphaBeth** [DmitriyAgeevP3131/313304#1]
https://github.com/DmitriyAgeevP3131/313304/blob/f2b29949f46fb2cbfbcac17084ae8244d3572f3b/Lab5/src/commands/RemoveByIdCommand.java#L28-L37

Бросать исключение, и тут же его перехватывать - плохая практика.

https://wiki.c2.com/?DontUseExceptionsForFlowControl

**Comment by AlphaBeth** [comment]
Уверен, что есть и в других местах.

**Comment by AgeDim** [comment]
Исправил как смог.

**Comment by AlphaBeth** [comment]
Лучше, но всё ещё под вопросом

**Comment by AlphaBeth** [comment]
IllegalStateException\NullPointerException

**Comment by AlphaBeth** [comment]
https://github.com/DmitriyAgeevP3131/313304/blob/e34e3d8164975082d1892c204e98cc5e5015c4e3/Lab5/src/run/App.java#L20-L22

https://github.com/DmitriyAgeevP3131/313304/blob/e34e3d8164975082d1892c204e98cc5e5015c4e3/Lab5/src/run/App.java#L47

**Comment by AlphaBeth** [comment]
https://github.com/DmitriyAgeevP3131/313304/blob/e34e3d8164975082d1892c204e98cc5e5015c4e3/Lab5/src/utility/Console.java#L57

https://github.com/DmitriyAgeevP3131/313304/blob/e34e3d8164975082d1892c204e98cc5e5015c4e3/Lab5/src/utility/Console.java#L71

https://github.com/DmitriyAgeevP3131/313304/blob/e34e3d8164975082d1892c204e98cc5e5015c4e3/Lab5/src/utility/Console.java#L83-L85
